import { createSlice } from '@reduxjs/toolkit';
import type { HeadersState } from '../../types/interfaces';

const initialState: HeadersState = {
  headers: [
    {
      id: 'h1',
      name: 'Host',
      value: '<calculated when request is sent>', // вычисляем значение при отправке запроса
      enabled: true,
      isAutoGenerated: true,
      isImmutable: true,
      isSensitive: false,
      source: 'auto',
    },
    {
      id: 'h2',
      name: 'User-Agent',
      value: 'RequestsFlow/1.0',
      enabled: true,
      isAutoGenerated: true,
      isImmutable: false,
      isSensitive: false,
      source: 'browser',
    },
    {
      id: 'h3',
      name: 'Accept',
      value: '*/*', // можно изменять
      enabled: true,
      isAutoGenerated: true,
      isImmutable: false,
      isSensitive: false,
      source: 'auto',
    },
    {
      id: 'h4',
      name: 'Accept-Encoding',
      value: 'identity', // потом добавить проверку ответа от сервера или добавить декодирование потом
      enabled: true,
      isAutoGenerated: true,
      isImmutable: true,
      isSensitive: false,
      source: 'auto',
    },
    {
      id: 'h5',
      name: 'Connection',
      value: 'keep-alive',
      enabled: true,
      isAutoGenerated: true,
      isImmutable: false,
      isSensitive: false,
      source: 'auto',
    },
    {
      id: 'h6',
      name: 'Cache-Control',
      value: 'no-cache',
      enabled: true,
      isAutoGenerated: true,
      isImmutable: true,
      isSensitive: false,
      source: 'auto',
    },
    {
      id: 'h7',
      name: 'Authorization',
      value: '',
      enabled: false,
      isAutoGenerated: false,
      source: 'user',
      isImmutable: false,
      isSensitive: true,
    },
    {
      id: 'h8',
      name: 'Cookie',
      value: '',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: true,
      source: 'user',
    },
    {
      id: 'h9',
      name: 'Content-Type',
      value: 'application/json; charset=utf-8',
      enabled: true,
      isAutoGenerated: true,
      isImmutable: true,
      isSensitive: false,
      meta: {
        appliesWhen: { methods: ['POST', 'PUT', 'PATCH'], bodyTypes: ['json'] }, // в дальнейшем поможет в логике добавления этого заголовка
      },
      source: 'auto',
    },
    {
      id: 'h10',
      name: 'Content-Length',
      value: '<calculated when request is sent>',
      enabled: true,
      source: 'auto',
      isAutoGenerated: true,
      isImmutable: false,
      isSensitive: false,
    },
    {
      id: 'h11',
      name: 'Transfer-Encoding',
      value: '',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: false,
      source: 'user',
    },
    {
      id: 'h12',
      name: 'Origin',
      value: '<calculated when request is sent>',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: false,
      source: 'browser',
    },
    {
      id: 'h13',
      name: 'Referer',
      value: '<calculated when request is sent>',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: false,
      source: 'browser',
    },
    {
      id: 'h14',
      name: 'Expect',
      value: '',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: false,
      meta: { appliesWhen: { bodySizeGt: 1048576 } }, // потом можно использовать в логике
      source: 'user',
    },
    {
      id: 'h15',
      name: 'If-None-Match',
      value: '"etag-value"',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: false,
      source: 'user',
    },
    {
      id: 'h16',
      name: 'X-Custom-Header',
      value: '',
      enabled: false,
      isAutoGenerated: false,
      isImmutable: false,
      isSensitive: false,
      source: 'user',
    },
  ],
  headersMap: {
    host: ['h1'],
    userAgent: ['h2'],
    accept: ['h3'],
    acceptEncoding: ['h4'],
    connection: ['h5'],
    cacheControl: ['h6'],
    authorization: ['h7'],
    cookie: ['h8'],
    contentType: ['h9'],
    contentLength: ['h10'],
    transferEncoding: ['h11'],
    origin: ['h12'],
    referer: ['h13'],
    expect: ['h14'],
    ifNoneMatch: ['h15'],
    xCustomHeader: ['h16'],
  },
};

const findHeaderById = (state: HeadersState, id: string) =>
  state.headers.find((h) => h.id === id);

const findHeaderByName = (state: HeadersState, name: string) =>
  state.headers.find((h) => h.name === name);

const headersSlice = createSlice({
  name: 'headers',
  initialState,
  reducers: {
    updateHeader(state, action) {
      const { headerName, newValue, enabled } = action.payload;
      const header = findHeaderByName(state, headerName);
      if (!header) return;
      if (header.isImmutable == false) {
        header.value = String(newValue);
        header.enabled = enabled;
        header.isAutoGenerated = false;
      }
    },
    toggleEnabled(state, action) {
      const { headerId } = action.payload;
      const header = findHeaderById(state, headerId);
      if (!header) return;
      header.enabled = !header.enabled;
    },
  },
});

export const { updateHeader, toggleEnabled } = headersSlice.actions;
export default headersSlice.reducer;
